version: "3.3"
services:

 vault:
  image: "vault:1.2.2"
  environment:
   - VAULT_DEV_ROOT_TOKEN_ID=myroot
  cap_add:
   - IPC_LOCK
  ports:
   - 8200:8200
  volumes:
   - "./vault/file:/vault/file"
   - "./vault/logs:/vault/logs"
 
